name: reviewdog
on: [pull_request]
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js with Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Set up yarn-global and install binary
        run: |
          mkdir -p ~/.yarn-global
          cd ~/.yarn-global
          echo "== Initializing yarn =="
          yarn init -y
          echo "== Adding mdx2vast =="
          yarn add mdx2vast
          echo "== Printing variable 1 =="
          echo $PATH
          echo "== Exporting variable =="
          echo "${HOME}/.yarn-global/node_modules/.bin" >> "$GITHUB_PATH"
          echo "== Printing variable 2 =="
          echo $PATH
      - name: Validate path
        run: |
          echo "PATH=$PATH"
          mdx2vast --version
      - name: Swap stuff
        run: |
          sudo apt-get install ripgrep
          rg -l0 '\$\[[^\]]*\]' -g '*.mdx' -g '*.md' . | xargs -0 perl -i -pe 's/\$\[[^\]]*\]/PICKLEVAR/g'
      - name: Run Vale with Reviewdog
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: false
